version: '2.1'
services:
  mafenix-api:
    build: .
    environment:
      PORT: '5500'
      SHOW_URLS: 'true'
      LISTS_URL: '192.168.99.101'
      LISTS_PORT: '4004'
      LISTS_ENTRY: 'lists-ms'
      ACTIVITIES_URL: '192.168.99.101'
      ACTIVITIES_PORT: '4000'
      ACTIVITIES_ENTRY: 'activities-ms/resources/activities'
      SCORERESOURCES_URL: '192.168.99.101'
      SCORERESOURCES_PORT: '5000'
      SCORERESOURCES_ENTRY: 'scoreservice'
      USERS_URL: '192.168.99.101'
      USERS_PORT: '3001'
      USERS_ENTRY: 'users'
      USERS_BY_EMAIL_ENTRY: 'users_by_email'
      USERS_SIGNUP_ENTRY: 'signup'
      USERS_LOGIN_ENTRY: 'login'
      USERS_VERIFY_JWT: 'verify_token'
      TRAILS_URL: '192.168.99.101'
      TRAILS_PORT: '3002'
      TRAILS_ENTRY: 'trails-ms'
    ports:
      - '5500:5500'
