version: '2.1'
services:
  academy-api:
    build: .
    environment:
      PORT: '5000'
      SHOW_URLS: 'true'
      ACTIVITIES_URL: '192.168.99.101'
      ACTIVITIES_PORT: '4000'
      ACTIVITIES_ENTRY: 'activities-ms/resources/activities'
    ports:
      - '5000:5000'
